// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0

namespace Authors

open System
open Fumble

type RowReader = SqliteRowReader

module Readers =

    let authorReader (r: RowReader) : Author =
        { Author.Id = r.int "id"
          Name = r.string "name"
          Bio = r.stringOrNone "bio" }
