// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0

namespace MAuthors

open System

type Employee = 
    {
        Id : int
        Name : string
        Occupation : string
        Age : int
    }

