// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0
// for nuget package Npgsql.FSharp --version 5.7.0

namespace Jets

open System
open Npgsql
open Npgsql.FSharp
open Jets.Readers

module Sqls =

  [<Literal>]
  let countPilots =
    """
    SELECT COUNT(*) FROM pilots
  """

  [<Literal>]
  let listPilots =
    """
    SELECT id, name FROM pilots LIMIT 5
  """

  [<Literal>]
  let deletePilot =
    """
    DELETE FROM pilots WHERE id = @id
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: string) =
  // https://www.connectionstrings.com/npgsql

  member this.countPilots() =

    conn
    |> Sql.connect
    |> Sql.query Sqls.countPilots
    |> Sql.executeRow (fun r -> r.int64 "count")

  member this.listPilots() =

    conn |> Sql.connect |> Sql.query Sqls.listPilots |> Sql.execute pilotReader

  member this.deletePilot(id: int) =

    let parameters = [ ("id", Sql.int id) ]

    conn
    |> Sql.connect
    |> Sql.query Sqls.deletePilot
    |> Sql.parameters parameters
    |> Sql.executeNonQuery
