// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0

namespace Ondeck

open System

type City = { Slug: string; Name: string }

type Venue =
    { Id: int64
      Status: venues_status
      Statuses: string option
      Slug: string
      Name: string
      City: string
      SpotifyPlaylist: string
      SongkickId: string option
      Tags: string option
      CreatedAt: DateTimeOffset }

type VenueCountByCityRow = { City: string; Count: int64 }
