// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0

namespace Booktest

open System

type Author = { AuthorId: int; Name: string }

type Book =
  {
    BookId: int
    AuthorId: int
    Isbn: string
    BookType: books_book_type
    Title: string
    Yr: int
    Available: DateTime
    Tags: string
  }

type BooksByTagsRow = { BookId: int; Title: string; Name: string option; Isbn: string; Tags: string }
