// Code generated by qtc from "queries.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line queries.qtpl:1
package templates

//line queries.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-fsharp/internal/core"
)

//line queries.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries.qtpl:6
func StreamQueries(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line queries.qtpl:6
	qw422016.N().S(`// Code generated by sqlc. DO NOT EDIT.
// version: sqlc `)
//line queries.qtpl:8
	qw422016.E().S(ctx.SqlcVersion)
//line queries.qtpl:8
	qw422016.N().S(`
`)
//line queries.qtpl:9
	if ctx.Settings.Engine == "sqlite" {
//line queries.qtpl:9
		qw422016.N().S(`// for nuget package Fumble --version 1.0.0
`)
//line queries.qtpl:11
	}
//line queries.qtpl:12
	if ctx.Settings.Engine == "postgresql" {
//line queries.qtpl:12
		qw422016.N().S(`// for nuget package Npgsql.FSharp --version 5.7.0
`)
//line queries.qtpl:14
	}
//line queries.qtpl:14
	qw422016.N().S(`

namespace `)
//line queries.qtpl:17
	qw422016.E().S(ctx.Package)
//line queries.qtpl:17
	qw422016.N().S(`

`)
//line queries.qtpl:19
	for _, mod := range core.Imports(ctx.SourceName, ctx.Package) {
//line queries.qtpl:19
		qw422016.N().S(`open `)
//line queries.qtpl:20
		qw422016.E().S(mod)
//line queries.qtpl:20
		qw422016.N().S(`
`)
//line queries.qtpl:21
	}
//line queries.qtpl:21
	qw422016.N().S(`
module Sqls = 
`)
//line queries.qtpl:24
	for _, query := range ctx.Queries {
//line queries.qtpl:24
		qw422016.N().S(`
  [<Literal>]
  let `)
//line queries.qtpl:26
		qw422016.N().S(query.ConstantName)
//line queries.qtpl:26
		qw422016.N().S(` =
    """
    `)
//line queries.qtpl:28
		qw422016.N().S(query.SQL)
//line queries.qtpl:28
		qw422016.N().S(`
  """
`)
//line queries.qtpl:30
	}
//line queries.qtpl:30
	qw422016.N().S(`
`)
//line queries.qtpl:32
	connstr := ctx.ConnString()

//line queries.qtpl:33
	qw422016.N().S(`
[<RequireQualifiedAccessAttribute>]
type DB (conn: string) =
`)
//line queries.qtpl:36
	for _, line := range connstr {
//line queries.qtpl:36
		qw422016.N().S(`  `)
//line queries.qtpl:37
		qw422016.N().S(line)
//line queries.qtpl:37
		qw422016.N().S(`
`)
//line queries.qtpl:38
	}
//line queries.qtpl:38
	qw422016.N().S(`

`)
//line queries.qtpl:41
	for _, query := range ctx.Queries {
//line queries.qtpl:41
		qw422016.N().S(`
  `)
//line queries.qtpl:43
		pipelines := ctx.ConnPipeline(query)

//line queries.qtpl:44
		qw422016.N().S(`

`)
//line queries.qtpl:46
		for _, line := range query.Comments {
//line queries.qtpl:46
			qw422016.N().S(`  ///`)
//line queries.qtpl:47
			qw422016.N().S(line)
//line queries.qtpl:47
			qw422016.N().S(`
`)
//line queries.qtpl:48
		}
//line queries.qtpl:48
		qw422016.N().S(`  member this.`)
//line queries.qtpl:49
		qw422016.E().S(query.ConstantName)
//line queries.qtpl:49
		qw422016.N().S(`  (`)
//line queries.qtpl:49
		qw422016.E().S(query.Arg.Args())
//line queries.qtpl:49
		qw422016.N().S(`) =

`)
//line queries.qtpl:51
		for _, line := range pipelines {
//line queries.qtpl:51
			qw422016.N().S(`    `)
//line queries.qtpl:52
			qw422016.N().S(line)
//line queries.qtpl:52
			qw422016.N().S(`
`)
//line queries.qtpl:53
		}
//line queries.qtpl:53
		qw422016.N().S(`
`)
//line queries.qtpl:55
	}
//line queries.qtpl:55
	qw422016.N().S(`

`)
//line queries.qtpl:57
}

//line queries.qtpl:57
func WriteQueries(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line queries.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries.qtpl:57
	StreamQueries(qw422016, ctx)
//line queries.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line queries.qtpl:57
}

//line queries.qtpl:57
func Queries(ctx core.TmplCtx) string {
//line queries.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line queries.qtpl:57
	WriteQueries(qb422016, ctx)
//line queries.qtpl:57
	qs422016 := string(qb422016.B)
//line queries.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line queries.qtpl:57
	return qs422016
//line queries.qtpl:57
}
