// Code generated by qtc from "readers.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line readers.qtpl:1
package templates

//line readers.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-fsharp/internal/core"
)

//line readers.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line readers.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line readers.qtpl:6
func StreamReaders(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line readers.qtpl:6
	qw422016.N().S(`
// Code generated by sqlc. DO NOT EDIT.
// version: sqlc `)
//line readers.qtpl:8
	qw422016.E().S(ctx.SqlcVersion)
//line readers.qtpl:8
	qw422016.N().S(`

namespace `)
//line readers.qtpl:10
	qw422016.E().S(ctx.Package)
//line readers.qtpl:10
	qw422016.N().S(`

`)
//line readers.qtpl:12
	for _, mod := range core.Imports(ctx.SourceName, ctx.Package) {
//line readers.qtpl:12
		qw422016.N().S(`open `)
//line readers.qtpl:13
		qw422016.E().S(mod)
//line readers.qtpl:13
		qw422016.N().S(`
`)
//line readers.qtpl:14
	}
//line readers.qtpl:14
	qw422016.N().S(`
`)
//line readers.qtpl:16
	if ctx.Settings.Engine == "sqlite" {
//line readers.qtpl:16
		qw422016.N().S(`
type RowReader = SqliteRowReader
`)
//line readers.qtpl:18
	}
//line readers.qtpl:18
	qw422016.N().S(`

module Readers =
`)
//line readers.qtpl:21
	for _, record := range ctx.ReaderSet() {
//line readers.qtpl:21
		qw422016.N().S(`
    `)
//line readers.qtpl:22
		qw422016.N().S(record)
//line readers.qtpl:22
		qw422016.N().S(`
`)
//line readers.qtpl:23
	}
//line readers.qtpl:23
	qw422016.N().S(`

`)
//line readers.qtpl:25
}

//line readers.qtpl:25
func WriteReaders(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line readers.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line readers.qtpl:25
	StreamReaders(qw422016, ctx)
//line readers.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line readers.qtpl:25
}

//line readers.qtpl:25
func Readers(ctx core.TmplCtx) string {
//line readers.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line readers.qtpl:25
	WriteReaders(qb422016, ctx)
//line readers.qtpl:25
	qs422016 := string(qb422016.B)
//line readers.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line readers.qtpl:25
	return qs422016
//line readers.qtpl:25
}
