// Code generated by qtc from "readers.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line readers.qtpl:1
package templates

//line readers.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-fsharp/internal/core"
)

//line readers.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line readers.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line readers.qtpl:6
func StreamReaders(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line readers.qtpl:6
	qw422016.N().S(`// Code generated by sqlc. DO NOT EDIT.
// version: sqlc `)
//line readers.qtpl:8
	qw422016.E().S(ctx.SqlcVersion)
//line readers.qtpl:8
	qw422016.N().S(`
`)
//line readers.qtpl:9
	if ctx.Settings.Engine == "sqlite" {
//line readers.qtpl:9
		qw422016.N().S(`// for nuget package Fumble --version 1.0.1
`)
//line readers.qtpl:11
	}
//line readers.qtpl:12
	if ctx.Settings.Engine == "postgresql" {
//line readers.qtpl:12
		qw422016.N().S(`// for nuget package Npgsql.FSharp --version 5.7.0
`)
//line readers.qtpl:14
	}
//line readers.qtpl:14
	qw422016.N().S(`
namespace `)
//line readers.qtpl:16
	qw422016.E().S(ctx.Package)
//line readers.qtpl:16
	qw422016.N().S(`

`)
//line readers.qtpl:18
	for _, mod := range core.Imports(ctx.SourceName, ctx.Package) {
//line readers.qtpl:18
		qw422016.N().S(`open `)
//line readers.qtpl:19
		qw422016.E().S(mod)
//line readers.qtpl:19
		qw422016.N().S(`
`)
//line readers.qtpl:20
	}
//line readers.qtpl:20
	qw422016.N().S(`
`)
//line readers.qtpl:22
	if ctx.Settings.Engine == "sqlite" {
//line readers.qtpl:22
		qw422016.N().S(`
type RowReader = SqliteRowReader
`)
//line readers.qtpl:24
	}
//line readers.qtpl:24
	qw422016.N().S(`

module Readers =
`)
//line readers.qtpl:27
	for _, record := range ctx.ReaderSet() {
//line readers.qtpl:27
		qw422016.N().S(`
    `)
//line readers.qtpl:28
		qw422016.N().S(record)
//line readers.qtpl:28
		qw422016.N().S(`
`)
//line readers.qtpl:29
	}
//line readers.qtpl:29
	qw422016.N().S(`

`)
//line readers.qtpl:31
}

//line readers.qtpl:31
func WriteReaders(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line readers.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line readers.qtpl:31
	StreamReaders(qw422016, ctx)
//line readers.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line readers.qtpl:31
}

//line readers.qtpl:31
func Readers(ctx core.TmplCtx) string {
//line readers.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line readers.qtpl:31
	WriteReaders(qb422016, ctx)
//line readers.qtpl:31
	qs422016 := string(qb422016.B)
//line readers.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line readers.qtpl:31
	return qs422016
//line readers.qtpl:31
}
