// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0

namespace Ondeck

open System
open Npgsql

type City = { Slug: string; Name: string }

type Venue =
  {
    Id: int
    Status: status
    Statuses: status
    Slug: string
    Name: string
    City: string
    SpotifyPlaylist: string
    SongkickId: string option
    Tags: string option
    CreatedAt: DateTime
  }

type VenueCountByCityRow = { City: string; Count: int64 }
