// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0
// for nuget package Npgsql.FSharp --version 5.7.0

namespace Authors

open System
open Npgsql
open Npgsql.FSharp

module Readers =

  let authorReader (r: RowReader) : Author =
    { Author.Id = r.int64 "id"; Name = r.text "name"; Bio = r.textOrNone "bio" }
